Employees/ViewModels/EmployerViewModel.cs
namespace Employees.ViewModels
{
    public class EmployerViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsFavourite { get; set; }
        public bool IsAvailable { get; set; }
    }
}

Employees/Controllers/EmployerController.cs
using BLL_Punonjes.Evente.Notification;
using BLL_Punonjes.Requests.AddOrEditRequests;
using BLL_Punonjes.Services.Scoped;
using BLL_Punonjes.Services.Singletone;
using DAL_Punonjes.Entities;
using Employees.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Employees.Controllers
{
    public class EmployerController : Controller
    {
        private readonly IEmployerService _employerService;
        private readonly IUserService _userService;
        private readonly ILoggerService _loggerService;
        private readonly IEmployerToUserService _employerToUserService;
        private readonly EmployerEventNotification _employerEventNotification;
        public EmployerController(
        IEmployerService employerService,
        IUserService userService,
        ILoggerService loggerService,
        IEmployerToUserService employerToUserService,
        EmployerEventNotification employerEventNotification
        )
        {
            _employerService = employerService;
            _userService = userService;
            _employerToUserService = employerToUserService;
            _loggerService = loggerService;
            _employerEventNotification = employerEventNotification;
            Initialize();
        }
        public void Initialize()
        {
            if (_employerEventNotification != null)
            {
                _employerService.EmployerChanged += _employerEventNotification.OnEmployerChanged;
            }
        }

        ////Delegat per shtim Punonjesi
        //public delegate void EmployerAdded(int id);
        ////Eventi per shtim Punonjesi i lidhur me delegatin me siper
        //public static event EmployerAdded OnEmployerAdded;

        ////Eventet
        //public static event OnEntityAdded OnEntityAdded;
        //public static event OnEntityUpdated OnEntityUpdated;
        //public static event OnEntityRemoved OnEntityRemoved;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var AllEmployees = _employerService.GetAllEmployees().Result.ToList();
                List<EmployerViewModel> employerViewModels = new List<EmployerViewModel>();
                int UserId = await _userService.GetIdByCurrentUser();
                foreach (var employee in AllEmployees)
                {
                    employerViewModels.Add(new EmployerViewModel
                    {
                        Id = employee.Id,
                        Name = employee.Name,
                        Description = employee.Description,
                        Adresa = employee.Adresa,
                        Email = employee.Email,
                        PhoneNumber = employee.PhoneNumber,
                        IsFavourite = await _employerToUserService.IsFavor(UserId, employee.Id),
                        IsAvailable = employee.IsAvailable
                    });
                }
               
                _loggerService.Log("Info", $"AllEmployer : {JsonConvert.SerializeObject(AllEmployees)}");
                return View(employerViewModels.ToList());
            }
            catch
            {
                throw;
            }
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View(new EmployerDTO { });
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployerDTO employerAddOrEditRequests)
        {
            if (!ModelState.IsValid)
            {
                return View(employerAddOrEditRequests);
            }
            else
            {
                try
                {
                    await _employerService.Create(employerAddOrEditRequests);
                    return RedirectToAction("Index");
                }
                catch
                {
                    throw;
                }
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var EmployerForUpdate = await _employerService.GetEmployerById(id);
                return View(new EmployerViewModel
                {
                    Id = EmployerForUpdate.Id,
                    Name = EmployerForUpdate.Name,
                    Email = EmployerForUpdate.Email,
                    Description = EmployerForUpdate.Description,
                    Adresa = EmployerForUpdate.Adresa,
                    PhoneNumber = EmployerForUpdate.PhoneNumber
                });
            }
            catch
            {
                throw;
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EmployerDTO employerAddOrEditRequests, int id)
        {
            if (!ModelState.IsValid)
            {
                return View(employerAddOrEditRequests);
            }
            try
            {
                await _employerService.Update(employerAddOrEditRequests, id);
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var EmployerForDetails = await _employerService.GetEmployerById(id);

                return View(new EmployerViewModel
                {
                    Id = EmployerForDetails.Id,
                    Name = EmployerForDetails.Name,
                    Description = EmployerForDetails.Description,
                    Adresa = EmployerForDetails.Adresa,
                    Email = EmployerForDetails.Email,
                    PhoneNumber = EmployerForDetails.PhoneNumber,
                });
            }
            catch
            {
                throw;
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _employerService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }
        [HttpGet]
        public async Task<IActionResult> ToggleEmployer(int id)
        {

            var userId = await _userService.GetIdByCurrentUser();
            if (userId != null)
            {
                await _employerToUserService.Toggle(userId, id);
            }
            else
            {
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

Employees/Views/Employer/Create.cshtml
@model BLL_Punonjes.Requests.AddOrEditRequests.EmployerDTO;

@{
    ViewData["Title"] = "Create Employer";
}

<h1>Create Car</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresa" class="control-label"></label>
                <input asp-for="Adresa" class="form-control" />
                <span asp-validation-for="Adresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Employees/Views/Employer/Delete.cshtml
@model DAL_Punonjes.Entities.Employer
@{
    ViewData["Title"] = "Delete Employer";
}

<h1>Delete Employer</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adresa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Employees/Views/Employer/Details.cshtml
@model Employees.ViewModels.EmployerViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adresa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Employees/Views/Employer/Edit.cshtml
@model Employees.ViewModels.EmployerViewModel
@{
    ViewData["Title"] = "Edit Employer";
}

<h1>Edit Car</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresa" class="control-label"></label>
                <input asp-for="Adresa" class="form-control" />
                <span asp-validation-for="Adresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Employees/Views/Employer/Index.cshtml
@model IEnumerable<Employees.ViewModels.EmployerViewModel>

@{
    ViewData["Title"] = "Employees Index";
}

<h2>@ViewData["Title"]</h2>
<p>
    <a class="btn btn-primary" asp-action="Create">
        <i class="fas fa-plus-circle"></i> Create New
    </a>
</p>

<div class="row">
    
    @foreach (var item in Model)
    {
        @if(item.IsAvailable){
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                    <p class="card-text">
                        <strong>Description: </strong>@Html.DisplayFor(modelItem => item.Description) <br />
                        <strong>Adresa: </strong>@Html.DisplayFor(modelItem => item.Adresa) <br />
                        <strong>Email: </strong>@Html.DisplayFor(modelItem => item.Email) <br />
                        <strong>Phone: </strong>@Html.DisplayFor(modelItem => item.PhoneNumber)
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@item.Id">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                            <a class="btn btn-sm btn-secondary" asp-action="Details" asp-route-id="@item.Id">
                                <i class="fas fa-info-circle"></i> Details
                            </a>
                            <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@item.Id">
                                <i class="fas fa-trash"></i> Delete
                            </a>
                            <a class="btn btn-outline-success" asp-controller="Reservation" asp-action="Create" asp-route-employerId="@item.Id">
                                <i class="fas fa-trash"></i> Rezervo
                            </a>
                            @{
                                if (!item.IsFavourite)
                                {
                                    <a class="btn btn-light" asp-controller="Employer" asp-action="ToggleEmployer" asp-route-id="@item.Id">Shto</a>  
                                }
                                else
                                {
                                    <a class="btn btn-light" asp-controller="Employer" asp-action="ToggleEmployer" asp-route-id="@item.Id">Hiq</a>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }
    }
</div>

<script>
    function addToFavorite(id) {
        alert("Item " + id + " added to favorites!");
        // Këtu mund të shtosh logjikë për të ruajtur në databazë ose lokalisht
    }
</script>